### ISSUE TITLE
Objeto usuário

### ISSUE THREAD

**Issue by programmerGM** [luandr/accessServer#35]
-Deve retornar um objeto do usuário
--No usuário, deve ter um objeto com os dados da pessoa
--- Na pessoa deve ter objetos com uma lista de telefones.
--- Deve ter também um objeto com o endereço, e no endereço deve ter um objeto da cidade.
-- Deve ter um objeto com o grupo, no grupo uma lista de objeto de permissão, e nesses objetos de permissão um objeto do grupo da permissão e o menu da permissão

**Comment by luandr** [comment]
No usuário, deve ter um objeto com os dados da pessoa:
Só retornar na query sql, cada usuário só pode ser uma pessoa, o resto vou ver

**Comment by luandr** [comment]
Falta o ultimo item amem
